# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ammar Shah
tagline:          'Fresh from my brain!'
description:      'I build things for the web. I also write sometimes.</br>'
url:              ammaralishah.github.io
baseurl:          /

author:
  name:           'Ammar Shah'
  url:            https://twitter.com/AmmarAliShahK

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
