# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ammar Shah
tagline:          'Freelance Developer and Writer'
description:      'I spend my time building things for the web or writing.</br> Editor-In-Chief & Founder @<a href="https://twitter.com/TheWormOfficial" target="_blank">The Worm Offical</a>'
url:              http://ammaralishah.me
baseurl:          /

author:
  name:           'Ammar Shah'
  url:            https://twitter.com/AmmarAliShahK

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
